## Testing the WECM algorithm with different values of gamma
### t0 = 1; t = t*gamma; gamma = 0.5, 0.4, 0.3, 0.2, 0.1

In [1]:
## Importing
import warnings

warnings.simplefilter(action='ignore', category=FutureWarning)
import numpy as np
from evclust.wecm_new import wecm
from evclust.utils import calculate_non_specificity
import pandas as pd
from sklearn.metrics import adjusted_rand_score
from ucimlrepo import fetch_ucirepo
from sklearn.preprocessing import LabelEncoder

# fetch dataset - IRIS
iris = fetch_ucirepo(id=53)

# data (as pandas dataframes)
X = iris.data.features
y = iris.data.targets

labels_encoder = LabelEncoder()
numeric_labels = labels_encoder.fit_transform(y['class'])
df = pd.concat([X, y], axis=1)

In [2]:
# Feature weighted ECM clustering
W = np.array([
    [0.07519226, 0.28935041, 0.16184003, 0.4736173],
    [0.09254051, 0.25118474, 0.4432175, 0.21305725],
    [0.22321534, 0.24617335, 0.0983041, 0.43230721]
])
c = 3
model = wecm(x=X, c=c, W=W, beta=2, alpha=1, delta=100, epsi=1e-3, ntrials=10, gamma=0.5)

# Compute the Adjusted Rand Index (ARI)
true_labels = numeric_labels
Y_betP = model['betp']
predicted_labels = np.argmax(Y_betP, axis=1)

ari = adjusted_rand_score(true_labels, predicted_labels)
print("----------Weighted ECM----------")
print(f"Jbest: {model['crit']}")
# print(f"Centers: \n {model['g']}")
# print(f"Final weights: \n{model['W']}")
# 
# print(f"Adjusted Rand Index (ARI): {ari}")
# 
# # Calculate Non-specificity
# calculate_non_specificity(model)

Initial weights: 
 [[0.07519226 0.28935041 0.16184003 0.4736173 ]
 [0.09254051 0.25118474 0.4432175  0.21305725]
 [0.22321534 0.24617335 0.0983041  0.43230721]]
---------Iteration #1---------
Initial prototypes: 
 [[5.9016129  2.7483871  4.39354839 1.43387097]
 [6.85       3.07368421 5.74210526 2.07105263]
 [5.006      3.418      1.464      0.244     ]]
Armijo condition: gamma = 0.5, #iterations = 4, step size = 0.0625
[1, 2.2797073857704855]
Armijo condition: gamma = 0.5, #iterations = 48, step size = 3.552713678800501e-15
[2, 2.2403561408731156]
Armijo condition: gamma = 0.5, #iterations = 47, step size = 7.105427357601002e-15
[3, 2.235042187500648]
Armijo condition: gamma = 0.5, #iterations = 46, step size = 1.4210854715202004e-14
[4, 2.2324793554837656]
Armijo condition: gamma = 0.5, #iterations = 47, step size = 7.105427357601002e-15
[5, 2.23083583362243]
Armijo condition: gamma = 0.5, #iterations = 47, step size = 7.105427357601002e-15
[6, 2.2296948783806183]
Armijo condition: ga

In [3]:
# gamma = 0.4
W = np.array([
    [0.07519226, 0.28935041, 0.16184003, 0.4736173],
    [0.09254051, 0.25118474, 0.4432175, 0.21305725],
    [0.22321534, 0.24617335, 0.0983041, 0.43230721]
])
c = 3
model_gamma04 = wecm(x=X, c=c, W=W, beta=2, alpha=1, delta=100, epsi=1e-3, ntrials=10, gamma=0.4)

# Compute the Adjusted Rand Index (ARI)
true_labels = numeric_labels
Y_betP = model_gamma04['betp']
predicted_labels = np.argmax(Y_betP, axis=1)

ari = adjusted_rand_score(true_labels, predicted_labels)
print("----------Weighted ECM----------")
print(f"Jbest: {model_gamma04['crit']}")
# print(f"Centers: \n {model_gamma04['g']}")
# print(f"Final weights: \n{model_gamma04['W']}")
# 
# print(f"Adjusted Rand Index (ARI): {ari}")
# 
# # Calculate Non-specificity
# calculate_non_specificity(model_gamma04)

Initial weights: 
 [[0.07519226 0.28935041 0.16184003 0.4736173 ]
 [0.09254051 0.25118474 0.4432175  0.21305725]
 [0.22321534 0.24617335 0.0983041  0.43230721]]
---------Iteration #1---------
Initial prototypes: 
 [[5.006      3.418      1.464      0.244     ]
 [6.85       3.07368421 5.74210526 2.07105263]
 [5.9016129  2.7483871  4.39354839 1.43387097]]
Armijo condition: gamma = 0.4, #iterations = 2, step size = 0.16000000000000003
Armijo condition: gamma = 0.4, #iterations = 40, step size = 1.2089258196146318e-16
[1, 2.305296820412312]
Armijo condition: gamma = 0.4, #iterations = 40, step size = 1.2089258196146318e-16
[2, 2.2640425657618866]
Armijo condition: gamma = 0.4, #iterations = 35, step size = 1.1805916207174135e-14
[3, 2.25770507129646]
Armijo condition: gamma = 0.4, #iterations = 35, step size = 1.1805916207174135e-14
[4, 2.253647820337224]
Armijo condition: gamma = 0.4, #iterations = 35, step size = 1.1805916207174135e-14
[5, 2.2503070824236606]
Armijo condition: gamma = 0.

In [6]:
# gamma = 0.3
W = np.array([
    [0.07519226, 0.28935041, 0.16184003, 0.4736173],
    [0.09254051, 0.25118474, 0.4432175, 0.21305725],
    [0.22321534, 0.24617335, 0.0983041, 0.43230721]
])
c = 3
model_gamma03 = wecm(x=X, c=c, W=W, beta=2, alpha=1, delta=100, epsi=1e-3, ntrials=10, gamma=0.3)

# Compute the Adjusted Rand Index (ARI)
true_labels = numeric_labels
Y_betP = model_gamma03['betp']
predicted_labels = np.argmax(Y_betP, axis=1)

ari = adjusted_rand_score(true_labels, predicted_labels)
print("----------Weighted ECM----------")
print(f"Jbest: {model_gamma03['crit']}")

Initial weights: 
 [[0.07519226 0.28935041 0.16184003 0.4736173 ]
 [0.09254051 0.25118474 0.4432175  0.21305725]
 [0.22321534 0.24617335 0.0983041  0.43230721]]
---------Iteration #1---------
Initial prototypes: 
 [[6.85       3.07368421 5.74210526 2.07105263]
 [5.9016129  2.7483871  4.39354839 1.43387097]
 [5.006      3.418      1.464      0.244     ]]
Armijo condition: gamma = 0.3, #iterations = 5, step size = 0.00243
[1, 2.2112404711876725]
Armijo condition: gamma = 0.3, #iterations = 28, step size = 2.2876792454960983e-15
[2, 2.1709488721715333]
Armijo condition: gamma = 0.3, #iterations = 30, step size = 2.0589113209464885e-16
[3, 2.1638228991810378]
Armijo condition: gamma = 0.3, #iterations = 27, step size = 7.625597484986994e-15
[4, 2.16007252278655]
Armijo condition: gamma = 0.3, #iterations = 27, step size = 7.625597484986994e-15
[5, 2.157338349141224]
Armijo condition: gamma = 0.3, #iterations = 30, step size = 2.0589113209464885e-16
[6, 2.1551860409015338]
Armijo condition:

In [8]:
# gamma = 0.2
W = np.array([
    [0.07519226, 0.28935041, 0.16184003, 0.4736173],
    [0.09254051, 0.25118474, 0.4432175, 0.21305725],
    [0.22321534, 0.24617335, 0.0983041, 0.43230721]
])
c = 3
model_gamma02 = wecm(x=X, c=c, W=W, beta=2, alpha=1, delta=100, epsi=1e-3, ntrials=10, gamma=0.2)

# Compute the Adjusted Rand Index (ARI)
true_labels = numeric_labels
Y_betP = model_gamma02['betp']
predicted_labels = np.argmax(Y_betP, axis=1)

ari = adjusted_rand_score(true_labels, predicted_labels)
print("----------Weighted ECM----------")
print(f"Jbest: {model_gamma02['crit']}")

Initial weights: 
 [[0.07519226 0.28935041 0.16184003 0.4736173 ]
 [0.09254051 0.25118474 0.4432175  0.21305725]
 [0.22321534 0.24617335 0.0983041  0.43230721]]
---------Iteration #1---------
Initial prototypes: 
 [[5.88360656 2.74098361 4.38852459 1.43442623]
 [6.85384615 3.07692308 5.71538462 2.05384615]
 [5.006      3.418      1.464      0.244     ]]
Armijo condition: gamma = 0.2, #iterations = 2, step size = 0.04000000000000001
[1, 2.2915772665559593]
Armijo condition: gamma = 0.2, #iterations = 19, step size = 5.2428800000000056e-14
[2, 2.2437149775732514]
Armijo condition: gamma = 0.2, #iterations = 20, step size = 1.0485760000000012e-14
[3, 2.2364076642486297]
Armijo condition: gamma = 0.2, #iterations = 20, step size = 1.0485760000000012e-14
[4, 2.2330146143434884]
Armijo condition: gamma = 0.2, #iterations = 20, step size = 1.0485760000000012e-14
[5, 2.230942275686787]
Armijo condition: gamma = 0.2, #iterations = 20, step size = 1.0485760000000012e-14
[6, 2.229559517164031]
Ar

In [15]:
# gamma = 0.1
W = np.array([
    [0.07519226, 0.28935041, 0.16184003, 0.4736173],
    [0.09254051, 0.25118474, 0.4432175, 0.21305725],
    [0.22321534, 0.24617335, 0.0983041, 0.43230721]
])
c = 3
model_gamma01 = wecm(x=X, c=c, W=W, beta=2, alpha=1, delta=100, epsi=1e-3, ntrials=10, gamma=0.1)

# Compute the Adjusted Rand Index (ARI)
true_labels = numeric_labels
Y_betP = model_gamma01['betp']
predicted_labels = np.argmax(Y_betP, axis=1)

ari = adjusted_rand_score(true_labels, predicted_labels)
print("----------Weighted ECM----------")
print(f"Jbest: {model_gamma01['crit']}")

Initial weights: 
 [[0.07519226 0.28935041 0.16184003 0.4736173 ]
 [0.09254051 0.25118474 0.4432175  0.21305725]
 [0.22321534 0.24617335 0.0983041  0.43230721]]
---------Iteration #1---------
Initial prototypes: 
 [[5.006      3.418      1.464      0.244     ]
 [5.9016129  2.7483871  4.39354839 1.43387097]
 [6.85       3.07368421 5.74210526 2.07105263]]
Armijo condition: gamma = 0.1, #iterations = 1, step size = 0.1
[1, 2.2600997263869878]
Armijo condition: gamma = 0.1, #iterations = 14, step size = 1.0000000000000008e-14
[2, 2.2196063850665753]
Armijo condition: gamma = 0.1, #iterations = 15, step size = 1.0000000000000009e-15
[3, 2.213723152576625]
Armijo condition: gamma = 0.1, #iterations = 15, step size = 1.0000000000000009e-15
[4, 2.210178683861845]
Armijo condition: gamma = 0.1, #iterations = 15, step size = 1.0000000000000009e-15
[5, 2.207261366095107]
Armijo condition: gamma = 0.1, #iterations = 15, step size = 1.0000000000000009e-15
[6, 2.204691399137365]
Armijo condition: ga