## Testing the WECM algorithm with different values of gamma
### t0 = 1; t = t*gamma; gamma = 0.5, 0.4, 0.3, 0.2, 0.1

In [3]:
## Importing
import warnings

warnings.simplefilter(action='ignore', category=FutureWarning)
import numpy as np
from evclust.wecm_new import wecm
from evclust.utils import calculate_non_specificity
import pandas as pd
from sklearn.metrics import adjusted_rand_score
from ucimlrepo import fetch_ucirepo
from sklearn.preprocessing import LabelEncoder

# fetch dataset - IRIS
iris = fetch_ucirepo(id=53)

# data (as pandas dataframes)
X = iris.data.features
y = iris.data.targets

labels_encoder = LabelEncoder()
numeric_labels = labels_encoder.fit_transform(y['class'])
df = pd.concat([X, y], axis=1)

In [21]:
# Feature weighted ECM clustering
W = np.array([
    [0.07519226, 0.28935041, 0.16184003, 0.4736173],
    [0.09254051, 0.25118474, 0.4432175, 0.21305725],
    [0.22321534, 0.24617335, 0.0983041, 0.43230721]
])
c = 3
model = wecm(x=X, c=c, W=W, beta=2, alpha=1, delta=100, epsi=1e-3, ntrials=1)

# Compute the Adjusted Rand Index (ARI)
true_labels = numeric_labels
Y_betP = model['betp']
predicted_labels = np.argmax(Y_betP, axis=1)

ari = adjusted_rand_score(true_labels, predicted_labels)
print("----------Weighted ECM----------")
print(f"Jbest: {model['crit']}")
# print(f"Centers: \n {model['g']}")
# print(f"Final weights: \n{model['W']}")
# 
# print(f"Adjusted Rand Index (ARI): {ari}")
# 
# # Calculate Non-specificity
# calculate_non_specificity(model)

Initial weights: 
 [[0.07519226 0.28935041 0.16184003 0.4736173 ]
 [0.09254051 0.25118474 0.4432175  0.21305725]
 [0.22321534 0.24617335 0.0983041  0.43230721]]
---------Iteration #1---------
Initial prototypes: 
 [[5.006      3.418      1.464      0.244     ]
 [5.9016129  2.7483871  4.39354839 1.43387097]
 [6.85       3.07368421 5.74210526 2.07105263]]
Armijo condition: gamma = 0.5, #iterations = 4, step size = 0.0625
Armijo condition: gamma = 0.5, #iterations = 45, step size = 2.842170943040401e-14
[1, 2.2600997263869878]
Armijo condition: gamma = 0.5, #iterations = 47, step size = 7.105427357601002e-15
[2, 2.218296689513349]
Armijo condition: gamma = 0.5, #iterations = 46, step size = 1.4210854715202004e-14
[3, 2.2118852539569245]
Armijo condition: gamma = 0.5, #iterations = 50, step size = 8.881784197001252e-16
[4, 2.2081281498321323]
Armijo condition: gamma = 0.5, #iterations = 48, step size = 3.552713678800501e-15
[5, 2.205098974651145]
Armijo condition: gamma = 0.5, #iterations 

In [22]:
# gamma = 0.4
W = np.array([
    [0.07519226, 0.28935041, 0.16184003, 0.4736173],
    [0.09254051, 0.25118474, 0.4432175, 0.21305725],
    [0.22321534, 0.24617335, 0.0983041, 0.43230721]
])
c = 3
model_gamma04 = wecm(x=X, c=c, W=W, beta=2, alpha=1, delta=100, epsi=1e-3, ntrials=1, gamma=0.4)

# Compute the Adjusted Rand Index (ARI)
true_labels = numeric_labels
Y_betP = model_gamma04['betp']
predicted_labels = np.argmax(Y_betP, axis=1)

ari = adjusted_rand_score(true_labels, predicted_labels)
print("----------Weighted ECM----------")
print(f"Jbest: {model_gamma04['crit']}")
# print(f"Centers: \n {model_gamma04['g']}")
# print(f"Final weights: \n{model_gamma04['W']}")
# 
# print(f"Adjusted Rand Index (ARI): {ari}")
# 
# # Calculate Non-specificity
# calculate_non_specificity(model_gamma04)

Initial weights: 
 [[0.07519226 0.28935041 0.16184003 0.4736173 ]
 [0.09254051 0.25118474 0.4432175  0.21305725]
 [0.22321534 0.24617335 0.0983041  0.43230721]]
---------Iteration #1---------
Initial prototypes: 
 [[5.006      3.418      1.464      0.244     ]
 [5.9016129  2.7483871  4.39354839 1.43387097]
 [6.85       3.07368421 5.74210526 2.07105263]]
Armijo condition: gamma = 0.4, #iterations = 3, step size = 0.06400000000000002
Armijo condition: gamma = 0.4, #iterations = 36, step size = 4.7223664828696544e-15
[1, 2.2600997263869878]
Armijo condition: gamma = 0.4, #iterations = 34, step size = 2.951479051793534e-14
[2, 2.218329098341523]
Armijo condition: gamma = 0.4, #iterations = 35, step size = 1.1805916207174135e-14
[3, 2.2119403235539736]
Armijo condition: gamma = 0.4, #iterations = 37, step size = 1.8889465931478618e-15
[4, 2.2081919569901176]
Armijo condition: gamma = 0.4, #iterations = 36, step size = 4.7223664828696544e-15
[5, 2.2051672971019722]
Armijo condition: gamma = 

In [24]:
# gamma = 0.3
W = np.array([
    [0.07519226, 0.28935041, 0.16184003, 0.4736173],
    [0.09254051, 0.25118474, 0.4432175, 0.21305725],
    [0.22321534, 0.24617335, 0.0983041, 0.43230721]
])
c = 3
model_gamma03 = wecm(x=X, c=c, W=W, beta=2, alpha=1, delta=100, epsi=1e-3, ntrials=1, gamma=0.3)

# Compute the Adjusted Rand Index (ARI)
true_labels = numeric_labels
Y_betP = model_gamma03['betp']
predicted_labels = np.argmax(Y_betP, axis=1)

ari = adjusted_rand_score(true_labels, predicted_labels)
print("----------Weighted ECM----------")
print(f"Jbest: {model_gamma03['crit']}")

Initial weights: 
 [[0.07519226 0.28935041 0.16184003 0.4736173 ]
 [0.09254051 0.25118474 0.4432175  0.21305725]
 [0.22321534 0.24617335 0.0983041  0.43230721]]
---------Iteration #1---------
Initial prototypes: 
 [[5.006      3.418      1.464      0.244     ]
 [5.9016129  2.7483871  4.39354839 1.43387097]
 [6.85       3.07368421 5.74210526 2.07105263]]
Armijo condition: gamma = 0.3, #iterations = 2, step size = 0.09
Armijo condition: gamma = 0.3, #iterations = 27, step size = 7.625597484986994e-15
[1, 2.2600997263869878]
Armijo condition: gamma = 0.3, #iterations = 29, step size = 6.863037736488295e-16
[2, 2.2191559586181215]
Armijo condition: gamma = 0.3, #iterations = 29, step size = 6.863037736488295e-16
[3, 2.213139585058636]
Armijo condition: gamma = 0.3, #iterations = 27, step size = 7.625597484986994e-15
[4, 2.2095396164123486]
Armijo condition: gamma = 0.3, #iterations = 27, step size = 7.625597484986994e-15
[5, 2.206592698249749]
Armijo condition: gamma = 0.3, #iterations = 3

In [31]:
# gamma = 0.2
W = np.array([
    [0.07519226, 0.28935041, 0.16184003, 0.4736173],
    [0.09254051, 0.25118474, 0.4432175, 0.21305725],
    [0.22321534, 0.24617335, 0.0983041, 0.43230721]
])
c = 3
model_gamma02 = wecm(x=X, c=c, W=W, beta=2, alpha=1, delta=100, epsi=1e-3, ntrials=1, gamma=0.2)

# Compute the Adjusted Rand Index (ARI)
true_labels = numeric_labels
Y_betP = model_gamma02['betp']
predicted_labels = np.argmax(Y_betP, axis=1)

ari = adjusted_rand_score(true_labels, predicted_labels)
print("----------Weighted ECM----------")
print(f"Jbest: {model_gamma02['crit']}")

Initial weights: 
 [[0.07519226 0.28935041 0.16184003 0.4736173 ]
 [0.09254051 0.25118474 0.4432175  0.21305725]
 [0.22321534 0.24617335 0.0983041  0.43230721]]
---------Iteration #1---------
Initial prototypes: 
 [[5.006      3.418      1.464      0.244     ]
 [5.9016129  2.7483871  4.39354839 1.43387097]
 [6.85       3.07368421 5.74210526 2.07105263]]
Armijo condition: gamma = 0.2, #iterations = 2, step size = 0.04000000000000001
Armijo condition: gamma = 0.2, #iterations = 3, step size = 0.008000000000000002
[1, 2.2600997263869878]
Armijo condition: gamma = 0.2, #iterations = 19, step size = 5.2428800000000056e-14
[2, 2.218066986934906]
Armijo condition: gamma = 0.2, #iterations = 20, step size = 1.0485760000000012e-14
[3, 2.211424632701517]
Armijo condition: gamma = 0.2, #iterations = 24, step size = 1.6777216000000023e-17
[4, 2.20758019811499]
Armijo condition: gamma = 0.2, #iterations = 20, step size = 1.0485760000000012e-14
[5, 2.204506262560161]
Armijo condition: gamma = 0.2, #

In [34]:
# gamma = 0.1
W = np.array([
    [0.07519226, 0.28935041, 0.16184003, 0.4736173],
    [0.09254051, 0.25118474, 0.4432175, 0.21305725],
    [0.22321534, 0.24617335, 0.0983041, 0.43230721]
])
c = 3
model_gamma01 = wecm(x=X, c=c, W=W, beta=2, alpha=1, delta=100, epsi=1e-3, ntrials=1, gamma=0.1)

# Compute the Adjusted Rand Index (ARI)
true_labels = numeric_labels
Y_betP = model_gamma01['betp']
predicted_labels = np.argmax(Y_betP, axis=1)

ari = adjusted_rand_score(true_labels, predicted_labels)
print("----------Weighted ECM----------")
print(f"Jbest: {model_gamma01['crit']}")

Initial weights: 
 [[0.07519226 0.28935041 0.16184003 0.4736173 ]
 [0.09254051 0.25118474 0.4432175  0.21305725]
 [0.22321534 0.24617335 0.0983041  0.43230721]]
---------Iteration #1---------
Initial prototypes: 
 [[5.9016129  2.7483871  4.39354839 1.43387097]
 [6.85       3.07368421 5.74210526 2.07105263]
 [5.006      3.418      1.464      0.244     ]]
Armijo condition: gamma = 0.1, #iterations = 2, step size = 0.010000000000000002
[1, 2.2797073857704855]
Armijo condition: gamma = 0.1, #iterations = 2, step size = 0.010000000000000002
[2, 2.2399647165844097]
Armijo condition: gamma = 0.1, #iterations = 13, step size = 1.0000000000000007e-13
[3, 2.2342058118811874]
Armijo condition: gamma = 0.1, #iterations = 17, step size = 1.000000000000001e-17
[4, 2.2315896189114177]
Armijo condition: gamma = 0.1, #iterations = 14, step size = 1.0000000000000008e-14
[5, 2.229925665922588]
Armijo condition: gamma = 0.1, #iterations = 16, step size = 1.000000000000001e-16
[6, 2.2287818527440537]
Armij