# Testing the convergence of weights of the new optimization method


In [1]:
## Importing
import warnings

warnings.simplefilter(action='ignore', category=FutureWarning)
import numpy as np
from evclust.wecm_old_search_direction import wecm
from evclust.datasets import load_letters
import pandas as pd
from ucimlrepo import fetch_ucirepo
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

## IRIS dataset

In [4]:
# fetch dataset - IRIS
iris = fetch_ucirepo(id=53)

# data (as pandas dataframes)
X = iris.data.features
y = iris.data.targets

# Normalization
scaler = MinMaxScaler((0,1))
X = pd.DataFrame(scaler.fit_transform(X))

# Weighted ECM clustering
c = 3
d = X.shape[1]
delta = np.sqrt(20)

model = wecm(x=X, c=c, g0=None, W=None, beta=2, alpha=1, delta=delta, epsi=1e-9, ntrials=1, init="non")
# 
# print(f"Final weights:\n {model['W']}")


Initial weights: 
 [[0.27724233 0.16142627 0.07996521 0.48136619]
 [0.38496686 0.32893858 0.17463998 0.11145459]
 [0.16858399 0.13899598 0.26769161 0.42472841]]
---------Iteration #1---------
Value of the step length: 0.5
New weights: 
 [[0.26362117 0.20571314 0.1649826  0.3656831 ]
 [0.31748343 0.28946929 0.21231999 0.18072729]
 [0.209292   0.19449799 0.25884581 0.33736421]]
Value of the step length: 0.25
New weights: 
 [[0.26021587 0.21678485 0.18623695 0.33676232]
 [0.30061257 0.27960197 0.22173999 0.19804547]
 [0.219469   0.20837349 0.25663435 0.31552315]]
Value of the step length: 1.7763568394002505e-15
New weights: 
 [[0.26021587 0.21678485 0.18623695 0.33676232]
 [0.30061257 0.27960197 0.22173999 0.19804547]
 [0.219469   0.20837349 0.25663435 0.31552315]]
Value of the step length: 0.5
New weights: 
 [[0.25510794 0.23339243 0.21811848 0.29338116]
 [0.27530629 0.26480098 0.23587    0.22402273]
 [0.2347345  0.22918675 0.25331718 0.28276158]]
Value of the step length: 0.5
New weight

## LetterIJL

In [5]:
# fetch dataset
df = load_letters()

# data (as pandas dataframes)
y = pd.DataFrame(df.iloc[:, -1])
X = df.iloc[:, :-1]

# Normalization
scaler = MinMaxScaler((0, 1))
X = pd.DataFrame(scaler.fit_transform(X))

c = 3
delta = np.sqrt(20)
model = wecm(x=X, c=c, g0=None, W=None, beta=2, alpha=1, delta=delta, epsi=1e-10, ntrials=1, init="non", disp=False)


Initial weights: 
 [[0.05975831 0.06484929 0.06722442 0.0343517  0.13455394 0.06382386
  0.01464098 0.06170227 0.08589534 0.05697061 0.06099343 0.12599163
  0.0078241  0.04119752 0.02333005 0.09689256]
 [0.14375832 0.01648646 0.03574345 0.06096573 0.11292932 0.08893095
  0.10573911 0.13944224 0.03520701 0.11309185 0.00356944 0.05097518
  0.01721595 0.03053789 0.04252076 0.00288633]
 [0.00118243 0.01615577 0.13825848 0.0788563  0.03120629 0.08250087
  0.06031258 0.05133379 0.09422546 0.17632649 0.09463959 0.01005404
  0.02227533 0.02753419 0.09590355 0.01923482]]
---------Iteration #1---------
Value of the step length: 0.5
New weights: 
 [[0.06112916 0.06367464 0.06486221 0.04842585 0.09852697 0.06316193
  0.03857049 0.06210113 0.07419767 0.05973531 0.06174671 0.09424581
  0.03516205 0.05184876 0.04291502 0.07969628]
 [0.10312916 0.03949323 0.04912173 0.06173287 0.08771466 0.07571547
  0.08411955 0.10097112 0.0488535  0.08779593 0.03303472 0.05673759
  0.03985797 0.04651895 0.05251038 0