# Testing the convergence of weights of the new optimization method


In [1]:
## Importing
import warnings

warnings.simplefilter(action='ignore', category=FutureWarning)
import numpy as np
from evclust.wecm_new import wecm
from evclust.datasets import load_letters
import pandas as pd
from ucimlrepo import fetch_ucirepo
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

## IRIS dataset

In [13]:
# fetch dataset - IRIS
iris = fetch_ucirepo(id=53)

# data (as pandas dataframes)
X = iris.data.features
y = iris.data.targets

# Normalization
scaler = MinMaxScaler((0,1))
X = pd.DataFrame(scaler.fit_transform(X))

# Weighted ECM clustering
c = 3
d = X.shape[1]
delta = np.sqrt(20)

model = wecm(x=X, c=c, g0=None, W=None, beta=2, alpha=1, delta=delta, epsi=1e-9, ntrials=1, init="non")

# print(f"Final weights:\n {model['W']}")


Initial weights: 
 [[0.20001049 0.15578682 0.22435263 0.41985006]
 [0.16083682 0.4466359  0.12098701 0.27154026]
 [0.18549011 0.17222166 0.01242992 0.62985831]]
---------Iteration #1---------
New weights: 
 [[0.22135841 0.19602039 0.23530529 0.34731591]
 [0.19891379 0.36266291 0.17608177 0.26234153]
 [0.21303894 0.20543676 0.11388378 0.46764052]]
New weights: 
 [[0.23139617 0.21493813 0.24045521 0.31321048]
 [0.21681751 0.32317895 0.20198723 0.25801631]
 [0.22599235 0.22105444 0.16158721 0.39136601]]
New weights: 
 [[0.23955302 0.23031101 0.24464012 0.28549585]
 [0.23136637 0.29109365 0.22303842 0.25450156]
 [0.2365185  0.23374561 0.20035179 0.3293841 ]]
New weights: 
 [[0.24642985 0.24327149 0.24816832 0.26213034]
 [0.24363215 0.26404333 0.24078616 0.25153836]
 [0.24539284 0.24444523 0.23303323 0.2771287 ]]
New weights: 
 [[0.24999991 0.24999982 0.24999995 0.25000032]
 [0.24999983 0.25000037 0.24999976 0.25000004]
 [0.24999988 0.24999985 0.24999955 0.25000072]]
New weights: 
 [[0.2499

## LetterIJL

In [8]:
# fetch dataset
df = load_letters()

# data (as pandas dataframes)
y = pd.DataFrame(df.iloc[:, -1])
X = df.iloc[:, :-1]

# Normalization
scaler = MinMaxScaler((0, 1))
X = pd.DataFrame(scaler.fit_transform(X))

c = 3
delta = np.sqrt(20)
model = wecm(x=X, c=c, g0=None, W=None, beta=2, alpha=1, delta=delta, epsi=1e-10, ntrials=1, init="non")


Initial weights: 
 [[0.06160219 0.05338146 0.0156391  0.03150522 0.07626349 0.02677341
  0.28906135 0.05538184 0.06961741 0.01189986 0.10738714 0.09145154
  0.00425432 0.02880014 0.06687286 0.01010866]
 [0.14025913 0.02499536 0.1583973  0.02202512 0.00905183 0.10542637
  0.0077928  0.03503263 0.00263705 0.0015345  0.31596988 0.03328054
  0.00314999 0.02222167 0.08036278 0.03786304]
 [0.13251803 0.12231289 0.0320842  0.12313486 0.14106387 0.00782558
  0.05544908 0.00970543 0.10010976 0.02184868 0.02634851 0.03822323
  0.02061817 0.00883813 0.13844666 0.02147292]]
---------Iteration #1---------
New weights: 
 [[0.06236524 0.06113136 0.05546643 0.05784785 0.06456583 0.05713763
  0.09650564 0.0614316  0.06356828 0.05490519 0.06923732 0.06684547
  0.05375764 0.05744183 0.06315634 0.05463634]
 [0.07417123 0.05687075 0.07689367 0.05642494 0.05447772 0.06894302
  0.05428874 0.0583773  0.05351489 0.05334941 0.10054447 0.05811432
  0.05359188 0.05645444 0.06518111 0.05880212]
 [0.07300933 0.0714